import { Montserrat } from '@next/font/google';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';
import Product from '../components/Product';
import { client } from '../lib/client';

const montserrat = Montserrat({ subsets: ['latin'] });

type Props = {
  products: any;
};

export default function Home({ products }: Props) {
  const { t } = useTranslation();

  console.log('products', products);
  return (
    <>
      <Head>
        <title>Alma Tapas</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        {/* <link rel='icon' href='/favicon.ico' /> */}
      </Head>
      <main className={montserrat.className}>
        {/* <h1>Alma Tapas</h1> */}
        <img className='logo' src='/logo.png' alt='Alma Tapas' />
        <h2>{t('main.toShare')}</h2>
        <ul>
          {products
            .filter((product: any) => product.type === 'to_share')
            .map((product: any) => (
              <Product key={product._id} product={product} />
            ))}
        </ul>
        <h2>{t('main.toContinue')}</h2>
        <ul>
          {products
            .filter((product: any) => product.type === 'to_continue')
            .map((product: any) => (
              <Product key={product._id} product={product} />
            ))}
        </ul>
        <h2>{t('main.forKids')}</h2>
        <ul>
          {products
            .filter((product: any) => product.type === 'for_kids')
            .map((product: any) => (
              <Product key={product._id} product={product} />
            ))}
        </ul>
      </main>
    </>
  );
}

export async function getStaticProps({ locale }: any) {
  const query = `*[_type == "product"]`;

  const products = await client.fetch(query);
  return {
    props: {
      products,
      ...(await serverSideTranslations(locale, ['common', 'main']))
    }
  };
}
