import { Montserrat } from '@next/font/google';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';
import Product from '../components/Product';
import { client } from '../lib/client';

const montserrat = Montserrat({ subsets: ['latin'] });

type Props = {
  products: any;
};

export default function Home({ products }: Props) {
  const { t } = useTranslation();
  const categories = ['to_share', 'to_continue', 'for_kids', 'dessert', 'wine_beer'];
  return (
    <>
      <Head>
        <title>Alma Tapas</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        {/* <link rel='icon' href='/favicon.ico' /> */}
      </Head>
      <main className={montserrat.className}>
        <img className='logo' src='/logo.png' alt='Alma Tapas' />
        {categories.map((category) => (
          <div className='category' key={category}>
            <h2>{t(`main.${category}`)}</h2>
            <ul>
              {products
                .filter((product: any) => product.type === category)
                .map((product: any) => (
                  <Product key={product._id} product={product} />
                ))}
            </ul>
          </div>
        ))}
      </main>
    </>
  );
}

export async function getStaticProps({ locale }: any) {
  const query = `*[_type == "product"]`;

  const products = await client.fetch(query);
  return {
    props: {
      products,
      ...(await serverSideTranslations(locale, ['common', 'main']))
    }
  };
}
